sudo: required
language: go

go:
 - 1.9
 - master

services:
  - docker

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq tree

script:
 - pushd teamcheck
 - go build
 - popd
 - ls -al
 - mkdir mattermost-docker
 - git clone https://github.com/mattermost/mattermost-docker.git mattermost-docker
 - pushd mattermost-docker
 - docker-compose build
 - docker-compose up -d
 - docker ps -a
 - docker-compose down
 - docker ps -a
 - popd
 - ls mattermost-docker
 - tree mattermost-docker
 - cp config.json mattermost-docker/volumes/app/mattermost/config/config.json
 - pushd mattermost-docker
 - docker-compose up -d
 - docker exec -it mattermostdocker_app_1 ./platform version
 - popd

