sudo: required
language: go

go:
 - 1.9
 - master

services:
  - docker

before_install:
  - ls
  - mkdir mattermost-docker
  - git clone https://github.com/mattermost/mattermost-docker.git mattermost-docker
  - cd mattermost-docker
  - docker-compose build
  - docker-compose up -d
  - docker ps -a

script:
 - go version
 - cd teamcheck
 - go build
